[블랙잭 1단계] 노명은 제출합니다
LIN-KHU/java-blackjack pull request #5
Opened 2024-01-29 12:41 UTC by NoMyeongEun

안녕하세요! 일요일부터 컨디션이 갑자기 너무 안 좋아져서 💦💦 요구 사항을 많이 못 맞춘 것 같아서 계속 수정해보겠습니다..!
처음에는 MVC 고려하다가, 뒤로 갈수록 일단 굴러가도록 했더니 완전 엉망진창인 것 같아요 🥲 우선 제출해보겠습니다..!

2024-01-30 04:44 UTC, woosung1223 requested changes
안녕하세요 명은님!

코드 깔끔하게 잘 짜주셨습니다!
컨디션 난조로 시간이 촉박하셨을텐데, 천천히 개선시켜보시기 바랍니다!

그리고 질문에 대한 답변을 드리자면..

> 뇌절이지만 "한장의 카드를 더 받겠습니까?(예는 y, 아니오는 n)" 여기에서 사람 이름에 따라 은/는 달라지는 거 어떻게 해야하나 잠시 심각하게 고민했었습니다... 이게 영어를 한글로 읽기 시작하면.. 😵‍💫

오.. 상당히 디테일한 고민입니다! 말씀드린 것처럼 은/는 을 고려할 필요는 있다고 보긴 하는데, 개인적으로는 뷰의 형태보다는 비즈니스 로직이 더욱 중요하다고 생각해서 일단은 우선순위를 낮쳐보셔도 좋을 것 같습니다.

> 모든 원시 값과 문자열을 포장하기, 일급 컬렉션 사용하기라는 요구 사항 지키려고 수정을 했는데.... 뭔가 이상한 것 같아요😑 크게 잘못한 느낌.. 잘못 이해한 느낌...

이 부분에 대해서는 '어떻게 하라' 라고 정답을 드리진 않겠습니다! 다만 일급 컬렉션이 '왜' 존재하는지를 먼저 파악하시고, 어떻게 적용시켜볼지 한 번 고민해보셨으면 좋겠습니다! 힌트를 드리자면, 컬렉션에 대한 비즈니스적인 행동을 캡슐화할 수 있는게 일급 컬렉션입니다. 

가령 나만의 규칙을 가진 Queue를 만들고 싶다면, Queue를 필드로 가지고 메소드마다 기타 규칙을 적용할 수 있겠죠? (add시, 개수가 100개가 넘지 않도록 한다 등) 

관련해서는 아주 유명한 글을 첨부드립니다! (https://jojoldu.tistory.com/412)

2024-01-30 04:44 UTC, woosung1223 commented on README.md
> +  - A(에이스)는 항상 11로 계산한다
이번에도 깔끔한 기능목록 💯
더 이상 기능목록은 이제 손볼 곳이 없다는 생각이 드네요!

다만 여쭤보고 싶은 점이, `딜러의 경우 에이스는 항상 11로 계산한다.` 라는 규칙은 요구사항에서 드러나지 않는 규칙이라 실제 블랙잭 규칙을 찾아봤는데요,

`The Dealer’s first ace counts as 11 unless it busts the hand. Subsequent aces count as one.` 이라는 규칙이 있네요! (참고: https://www.thecasinolsq.com/assets/empire/images/files/blackjack_8_deck.pdf)

딜러도 플레이어와 마찬가지로 21을 넘는다면 Ace를 1로 사용할 수 있다는 것 같습니다.

다만 기능목록을 실제 도메인 지식과 연결시켜 작성하셨다는 점은 놀라웠고, 칭찬받아 마땅할 부분이라는 생각이 듭니다! 👍👍

2024-01-30 04:44 UTC, woosung1223 commented on src/main/java/blackjack/view/InputView.java
> +    Scanner scanner;
접근제어자 부탁드립니다!

2024-01-30 04:44 UTC, woosung1223 commented on src/main/java/blackjack/view/InputView.java
> +                throw new IllegalArgumentException();
예외에도 가급적 의미를 담는게 좋습니다.

가령 예외 메세지가 있다면 stack trace를 활용해 디버깅하기도 좋겠죠!

2024-01-30 04:44 UTC, woosung1223 commented on src/main/java/blackjack/Game.java
> +    private final GameController game;
Game이 GameController에 의존하는 구조네요.

이 경우는 GameController는 InputView, OutputView에 의존하고 있으므로 Game이 InputView에 간접적으로 의존하는 경우입니다!

즉, 모델과 뷰가 적절히 분리되지 못한 케이스에요! 서비스의 중심이 되는 핵심 비즈니스 로직들이 입출력의 변화에 영향을 받는다는 의미입니다.

입출력은 변화하더라도 서비스의 핵심 규칙이 변화하지 않도록 설계하는게 중요합니다. 왜 그런지는 스스로 한 번 생각해보세요!

그리고 한 번 GameController가 Game을 사용하는 쪽으로 개선해보세요 😄

2024-01-30 04:44 UTC, woosung1223 commented on src/main/java/blackjack/controller/GameController.java
> +        if (player.getWin() == 1) {
getWin()이 1을 반환하는 순간은 어느 순간인가요?

`이겼다`를 표현하고 싶으시다면 boolean값 반환 + `isWin` 등의 메소드명이 적절해보입니다!

2024-01-30 04:44 UTC, woosung1223 commented on src/main/java/blackjack/Participant.java
> +    }
생성자 체이닝에 대해 검색해보세요!

2024-01-30 04:44 UTC, woosung1223 commented on src/main/java/blackjack/Participant.java
> +
Setter를 지양하는 쪽으로 리팩토링 해보시길 바랍니다!

비즈니스적으로 의미가 있는 Setter라면 모르겠지만, 일반적인 경우 필드 값 재설정은 캡슐화를 무너뜨리고 객체지향적인 설계에 방해가 되는 편입니다!

2024-01-30 04:44 UTC, woosung1223 commented on src/main/java/blackjack/Deck.java
> +    }
매번 가장 위에 있는 카드를 꺼내는 것이라면, List보다는 Queue가 더 적절한 자료구조겠네요 😄

2024-01-30 04:44 UTC, woosung1223 commented on src/main/java/blackjack/CardScore.java
> +    public boolean checkIfAce() { return (cardScore == 'A'); }
String끼리의 동일성 비교는 일반적으로 권장되지 않습니다!

동등성 & 동일성에 대해 찾아보시고, String이 왜 동일성 비교를 하면 안되는지에 대해서도 고민해보세요!

2024-02-03 17:47 UTC, NoMyeongEun commented
__________1단계 __________

2024-02-04 06:33 UTC, NoMyeongEun commented on README.md
> +  - A(에이스)는 항상 11로 계산한다
앗 저도 구글링 하다가 읽은 글 보고 넣었던 내용인데, 제가 이해를 잘못하고 있었나봐요🥲 정정해주셔서 감사합니다🙇‍♂️🙇‍♂️

2024-02-04 06:35 UTC, NoMyeongEun commented on src/main/java/blackjack/CardScore.java
> +    public boolean checkIfAce() { return (cardScore == 'A'); }
엇 저건 String이 아니고 char이었던 것 같은데 수정해야하나요..? 그래도 동등성, 동일성 찾아보면서 공부했습니다!✍🏻✍🏻

2024-02-04 06:48 UTC, woosung1223 commented on src/main/java/blackjack/CardScore.java
> +    public boolean checkIfAce() { return (cardScore == 'A'); }
`cardScore == 'A'` 부분을 제가 String 비교로 봤었네요! 착오였던 것 같습니다 죄송합니다! 🙇‍♂️

제가 리뷰를 잘못드린 부분을 잘 찾아주셨네요 💯

2024-02-04 07:14 UTC, NoMyeongEun commented
안녕하세요! 이번 리뷰 반영에서 느낀 교훈은 "처음부터 잘 하자"였습니다... 이상하게 짠 구조를 수정하려니까 너무 힘들었어요 💦💦 
2단계 내용도 조금 하다가 이미 한참 늦은 뒤라.. 우선 잠깐 끊어가보겠습니다..! 남은 기간에는 강의에서 배웠던 테스트에 집중해볼까 합니다..

1. 은/는 뇌절은 그냥 단순한 호기심에 (정말로 영어로 되어있어도 은/는을 잘 할 수 있는 규칙성이 있을지 궁금했어요) 잠깐 찾아봤는데, 법칙이 있긴 하지만 너무 복잡해서 읽는 순간 바로 포기했습니다ㅎㅎ

> 모든 원시 값과 문자열을 포장한다

2. 해당 요구사항이 "모든" 이어서 몇 개는 하면서도 왜 좋은지 잘 알지 못했는데, 폴더 구조도 Card, Game, Participant로 구분하고 정리하니까 조금은 감이 잡히는 것 같습니다.. 하지만 아직 잘 모르겠어요🤷

> 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

⭐️ 3. 그리고 다른 프로그래밍 요구사항이었던 내용인데, 아무래도 Participant 클래스 쪽에 인스턴스 변수가 많이 생기게 되었는데 이걸 어떻게 해결하면 좋을까요..? 그 외에도 Game이나 GameController도 3개 인스턴스 변수를 갖는데 특히 GameController와 같은 경우에는 View인 InputView와 OutputView와 Model인 Game만 해도 3개가 되는데... 해결 방법을 잘 떠올리지 못하겠어서 일단 그대로 두었습니다🥲

> 게임에 참여할 사람의 이름을 입력하세요.(쉼표 기준으로 분리)

4. 이건 멘토님들이 예전에 하셨던 코드들이나 다른 분들이 하신 것들 보면서 생각했던 점인데, InputView와 OutputView에서 궁금한 점이 있습니다! 위처럼 입력받기 위한 문구는 그냥 상수로 선언하고 Input에서 출력하도록 하는 게 좋은 방향인가요? 

>`output.printCardSharedMessage(game.getPlayerList());`
`output.printDealerInitialCardList(game.getDealer());`
`output.printPlayersInitialCardList(game.getPlayerList());`

5. OutputView에서 이렇게 막 여러개의 내용?을 출력해야하는 경우에 이걸 OutputVIew에서 미리 묶어?두는 것말고 이렇게 Controller에서 3번씩 output 찍는게 좋은 방식인지 모르겠습니다..

3번 말고는 하면서 들었던 사소한 궁금증...입니다. MVC 잘 수정하려고 몇일을 고민했더니 생각보다 너무 오래 걸렸네요😭 제발 잘 바꾼 게 맞기를..바랍니다.. 배팅 룰도 아직 헷갈리긴 한데..😵‍💫 2단계도 나중에 꼭 해보고 싶어요..

2024-02-04 09:36 UTC, woosung1223 requested changes
안녕하세요 명은님!!

자동차 경주 미션때부터 봤지만, 한 달만에 이정도로 성장하다니.. 많이 놀랍습니다! 과거의 저보다 빠르게 성장하시는 것 같습니다 💯

리뷰 남겨드렸는데, 말씀해주신 질문에 대한 답변도 남겨드리도록 하겠습니다.

> 모든 원시 값과 문자열을 포장한다

> 해당 요구사항이 "모든" 이어서 몇 개는 하면서도 왜 좋은지 잘 알지 못했는데, 폴더 구조도 Card, Game, Participant로 구분하고 정리하니까 조금은 감이 잡히는 것 같습니다.. 하지만 아직 잘 모르겠어요🤷

물론 요구사항 자체가 '모든' 원시 값과 문자열을 포장하라고 했지만, 정말로 모든 것을 객체화하는게 좋을까요? 명은님이 실제로 느끼기에는 '이상하다'고 판단되는 부분이 있지 않으셨나요?

해당 요구사항은 (제 생각에는) 객체 분리를 체화시키기 위해 존재하는 것 같습니다. '과연 이걸 객체로 분리하는게 맞을까?' 라는 고민을 직접 느껴보시면 깨닫는게 많아서요!

> 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

> ⭐️ 3. 그리고 다른 프로그래밍 요구사항이었던 내용인데, 아무래도 Participant 클래스 쪽에 인스턴스 변수가 많이 생기게 되었는데 이걸 어떻게 해결하면 좋을까요..? 그 외에도 Game이나 GameController도 3개 인스턴스 변수를 갖는데 특히 GameController와 같은 경우에는 View인 InputView와 OutputView와 Model인 Game만 해도 3개가 되는데... 해결 방법을 잘 떠올리지 못하겠어서 일단 그대로 두었습니다🥲

우선 Game에서는 Participant와 PlayerList가 과연 전부 필요할까요? 한 번 고민해보시면 줄일 수 있을 것 같습니다!

그리고 컨트롤러 같은 경우는 말씀해주신대로 어쩔 수 없긴 하죠.. InputView나 OutputView를 static하게 사용하는게 대안이 되겠다만, 딱히 의미는 없어보입니다. 이런 경우라면 요구사항을 지키지 않아도 괜찮을 것 같습니다!

> 이건 멘토님들이 예전에 하셨던 코드들이나 다른 분들이 하신 것들 보면서 생각했던 점인데, InputView와 OutputView에서 궁금한 점이 있습니다! 위처럼 입력받기 위한 문구는 그냥 상수로 선언하고 Input에서 출력하도록 하는 게 좋은 방향인가요?
output.printCardSharedMessage(game.getPlayerList());
output.printDealerInitialCardList(game.getDealer());
output.printPlayersInitialCardList(game.getPlayerList());

저는 개인적으로 '입력을 위한 출력'은 InputView에 위치하는게 좋다 봅니다. 만약 입력 메세지를 바꿔야 하는 상황이 왔는데, OutputView를 수정해야 한다면 그렇게 논리적이지는 않은 것 같아요. 

또한 책임의 관점으로 본다면 InputView의 책임은 '입력'이고, 해당 '입력'이라는 책임을 수행하기 위한 방법이 '입력을 위한 출력'이므로 InputView에서 출력하는게 나을 것 같습니다!

> OutputView에서 이렇게 막 여러개의 내용?을 출력해야하는 경우에 이걸 OutputVIew에서 미리 묶어?두는 것말고 이렇게 Controller에서 3번씩 output 찍는게 좋은 방식인지 모르겠습니다..

이 부분은 관련해서 코멘트 남겼습니다!

2024-02-04 09:36 UTC, woosung1223 commented on src/main/java/blackjack/PlayerNameList.java
> +                throw new IllegalArgumentException("공백으로만 이뤄지지 않은 한 명 이상의 이름이 입력되어야 합니다.");
예외 메세지를 의미가 드러나도록 잘 넣어주셨네요 👍

예외에 대한 기본적인 개념은 이해하신 것 같으니, 한 가지 질문을 드리고자 합니다!

커스텀 예외와 표준 예외는 각각 언제 사용하는 게 좋을까요?

2024-02-04 09:36 UTC, woosung1223 commented on src/main/java/blackjack/Deck.java
> +        this.deckList= new LinkedList<>(cardList);
cardList를 처음부터 ArrayList가 아닌 LinkedList로 초기화하면 

`this.deckList = new LinkedList<>(cardList)`와 같이 생성자를 통한 복사가 발생하지 않아도 될 것 같습니다!

직접 LinkedList의 생성자 구현부에 들어가보시면 아시겠지만, 다음과 같은 형태로 모든 원소를 하나씩 추가해주기 때문에 불필요한 비용이 생성됩니다.

```java
public LinkedList(Collection<? extends E> c) {
    this();
    addAll(c);
}
```

addAll의 javaDocs에는 다음과 같은 내용도 적혀있네요~

`Inserts all of the elements in the specified collection into this list.`

2024-02-04 09:36 UTC, woosung1223 commented on src/main/java/blackjack/Score.java
>              this.score += checkCardScore(card);
`checkCardScore`라는 메소드명과 달리, int 형 반환값을 제공하고 있네요.

이런 경우 '어떤 값을 반환하는거지?' 라는 고민이 생기게 되고, 구현부에 직접 들어가고 나서야 '카드 숫자를 반환하는구나!' 라는 생각이 들게 됩니다!

현재 `check ... ` 라는 메소드명은 boolean 값 반환 용도로도 사용되고 있는데, 통용하면 좋을 듯 합니다!

2024-02-04 09:36 UTC, woosung1223 commented on src/main/java/blackjack/controller/GameController.java
> +    public void start() {
메소드와 메소드 사이에는 개행을 추가해주시길 바랍니다!

2024-02-04 09:36 UTC, woosung1223 commented on src/main/java/blackjack/model/Game/Game.java
> +        dealer.getNewCard(deck);
일반적으로 `get...` `set...` 등과 같은 메소드명은 Java에서 필드를 그대로 가져오거나, 수정하는 작업을 수행합니다.

`setupIntialCards`, `drawCard` 등과 같은 메소드명은 어떤가요?

또한 메소드명을 지을 때에는 도메인의 개념을 잘 포함하는 단어를 선택하는게 좋습니다.

카드를 뽑는 메소드는 그럼 get보다는 draw가 더 도메인 집약적인 표현이 가능하겠죠!

2024-02-04 09:36 UTC, woosung1223 commented on src/main/java/blackjack/controller/GameController.java
> +    }
y, n 을 입력하는 과정은 `askPlayerIsExit` 보다는 `askPlayerIfDraw` 등과 같은 메소드명이 더 어울릴 것 같습니다! 카드를 안 뽑는다고 해서 게임을 나가는 건 아니니까요 😄

2024-02-04 09:36 UTC, woosung1223 commented on src/main/java/blackjack/controller/GameController.java
> +        game.getResult();
게임에서 점수는 계산하는데, 결과값을 반환하지 않는 경우가 있을까요?

반대로 말씀드리면, 두 메소드가 나타내는 행위는 하나의 원자적인 단위가 아닐까요?!

그렇다면 굳이 메소드 분리가 필요 없겠네요 🤔

2024-02-04 09:36 UTC, woosung1223 commented on src/main/java/blackjack/controller/GameController.java
> +    }
이 부분은 컨트롤러에서 굳이 담당하지 않아도 될 것 같습니다.

OutputView의 책임에 더욱 가까워보여요!

'어떻게 보여질지'를 가공하고 있으므로 OutputView에게 책임을 전달하는 편이 나아보입니다 🙂

2024-02-04 09:36 UTC, woosung1223 commented on src/main/java/blackjack/model/Game/Game.java
> +        }
명령과 조회는 분리되는 편이 좋습니다.

얼핏보면 boolean 값을 반환하는 상태검증 메소드로 보이는데, 내부적으로는 딜러의 점수가 17점 이하이면 한 장 더 뽑도록 되어 있네요!

이 경우 예측 불가능한 행동을 만들고, 유지보수 및 디버깅 시 어려움을 겪기가 쉽습니다~!

https://en.wikipedia.org/wiki/Command%E2%80%93query_separation

2024-02-04 09:36 UTC, woosung1223 commented on src/main/java/blackjack/model/Game/Game.java
> +        return (dealer.getScore() > 21) || (player.getScore() <= 21 && dealer.getScore() <= player.getScore());
score에 대한 정보는 dealer, player 각각이 가지고 있는 것으로 보여요.

이 경우 Game이라는 객체가 21이라는 숫자에 대해 알 필요가 있을까요?

TDA 원칙 혹은 Information Expert 패턴에 대해 찾아보시고, `dealer.isBust()` 등과 같은 메소드로 개선해보시기 바랍니다!

2024-02-14 10:01 UTC, merged